name: nope-tensorf-new
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.8
  - cudatoolkit=11.8
  - pytorch=2.0.0
  - torchvision=0.15.2
  # - python=3.8
  # - pytorch=2.0.1
  # - torchvision=0.15.2 
  # - torchaudio=2.0.2
  # - cudatoolkit=11.8 
  # - python=3.9
  # - pytorch=1.7
  # - torchvision=0.8.2 
  # - torchaudio 
  # - cudatoolkit=10.1 # 10.1 -> 11.8
  - cffi
  - cython
  - imageio
  - numpy
  - scipy
  - matplotlib
  - pandas
  - tensorboard
  - yaml
  - pillow
  - wheel
  - pip
  - tqdm
  - pip:
    - ipdb
    - ipython
    - ipython-genutils
    - jedi
    - opencv-python
    - scikit-image
    - pyyaml
    - trimesh
    - imageio
    - matplotlib
    - plyfile
    - timm
    - lpips
    - setuptools
    - kornia==0.5.0
    - imageio-ffmpeg
    ### tensorf
    - configargparse 